<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project default="build_jar" name="Create all Jars for Project RestClient">
	<property name="mailapi.version" value="2.0.1" />
	<property name="json.version" value="26.2.1" />
	<property name="proxyautoconfig.version" value="26.1.0" />
	<property name="network.version" value="26.0.27" />
	<property name="soderer-utilities.version" value="26.2.39" />

	<property name="swt.version" value="4.38" />
	<property name="swt.build" value="R-4.38-202512010920" />
	
	<target name="build_jar" depends="build_setup, cleanup_before, create_jar, sign_jar, cleanup_after" />

	<target name="probe-proxy">
		<condition property="proxy.enabled">
			<and>
				<isset property="proxy.host" />
			</and>
		</condition>
	</target>

	<target name="proxy" depends="probe-proxy" if="proxy.enabled">
		<property name="proxy.port" value="80" />
		<property name="proxy.user" value="" />
		<property name="proxy.pass" value="" />
		<setproxy proxyhost="${proxy.host}" proxyport="${proxy.port}" proxyuser="${proxy.user}" proxypassword="${proxy.pass}" />
	</target>
	
	<available file="${user.home}/git/codeSigning.properties" property="codeSigningPropertiesAvailable" />

	<target name="build_setup">
		<echo>Java/JVM HOME: ${java.home}</echo>
		<echo>Java/JVM version: ${ant.java.version}</echo>
		<echo>Java/JVM detailed version: ${java.version}</echo>

		<loadfile property="build.version" srcFile="build.version" failonerror="false" />
		<property name="build.version" value="26.0.0" />
		<echo message="build.version: ${build.version}" />

		<!-- Default: https://soderer.de/index.php?download=Versions.json -->
		<!-- Override for GitHub: https://api.github.com/repos/hudeany/RestClient/releases/latest -->
		<property name="VersionsUrl" value="https://api.github.com/repos/hudeany/RestClient/releases/latest" />
		<property file="${user.home}/git/codeSigning.properties" />

		<property environment="env"/>

		<tstamp>
			<format property="buildTime" pattern="yyyy-MM-dd HH:mm:ss" locale="en" />
		</tstamp>
		<echo message="buildTime: ${buildTime}" />

		<property file="${user.home}/git/codeSigning.properties" />

		<property name="buildPath" value="build" />
		<echo message="buildPath: ${buildPath}" />

		<condition property="HOME" value="${user.home}">
			<and>
				<isset property="user.home" />
				<available file="${user.home}" type="dir" />
			</and>
		</condition>
		<condition property="HOME" value="${env.HOME}">
			<and>
				<isset property="env.HOME" />
				<available file="${env.HOME}" type="dir" />
			</and>
		</condition>
		<fail message="Property &quot;env.HOME&quot; or &quot;user.home&quot; was not set properly" unless="HOME" />
	</target>

	<target name="cleanup_before">
		<delete dir="${buildPath}" />
		<mkdir dir="${buildPath}" />
		<mkdir dir="${buildPath}/bin" />
	</target>

	<available file="lib/mailapi-${mailapi.version}.jar" property="mailapi.available" />
	<target name="get_mailapi" unless="mailapi.available" depends="proxy">
		<mkdir dir="lib/" />
		<delete>
			<fileset dir="lib" includes="mailapi-*.jar" />
		</delete>
		<get src="https://repo1.maven.org/maven2/com/sun/mail/mailapi/${mailapi.version}/mailapi-${mailapi.version}.jar" dest="lib/" />
	</target>

	<available file="lib/json-${json.version}.jar" property="json.available" />
	<target name="get_json" unless="json.available" depends="proxy">
		<mkdir dir="lib/" />
		<delete>
			<fileset dir="lib" includes="json-*.jar" />
		</delete>
		<get src="https://github.com/hudeany/json/releases/download/${json.version}/json-${json.version}.jar" dest="lib/" />
	</target>

	<available file="lib/proxyautoconfig-${proxyautoconfig.version}.jar" property="proxyautoconfig.available" />
	<target name="get_proxyautoconfig" unless="proxyautoconfig.available" depends="proxy">
		<mkdir dir="lib/" />
		<delete>
			<fileset dir="lib" includes="proxyautoconfig-*.jar" />
		</delete>
		<get src="https://github.com/hudeany/ProxyAutoConfig/releases/download/${proxyautoconfig.version}/proxyautoconfig-${proxyautoconfig.version}.jar" dest="lib/" />
	</target>

	<available file="lib/network-${network.version}.jar" property="network.available" />
	<target name="get_network" unless="network.available" depends="proxy">
		<mkdir dir="lib/" />
		<delete>
			<fileset dir="lib" includes="network-*.jar" />
		</delete>
		<get src="https://github.com/hudeany/network/releases/download/${network.version}/network-${network.version}.jar" dest="lib/" />
	</target>

	<available file="lib/soderer-utilities-${soderer-utilities.version}.jar" property="soderer-utilities.available" />
	<target name="get_soderer_utilities" unless="soderer-utilities.available" depends="proxy">
		<mkdir dir="lib/" />
		<delete>
			<fileset dir="lib" includes="soderer-utilities-*.jar" excludes="soderer-utilities-*-sources.jar" />
		</delete>
		<get src="https://soderer.de/maven2/de/soderer/JavaUtilities/${soderer-utilities.version}/soderer-utilities-${soderer-utilities.version}.jar" dest="lib/" />
	</target>

	<available file="lib/soderer-utilities-${soderer-utilities.version}-sources.jar" property="soderer-utilities-sources.available" />
	<target name="get_soderer_utilities_sources" unless="soderer-utilities-sources.available" depends="proxy">
		<mkdir dir="lib/" />
		<delete>
			<fileset dir="lib" includes="soderer-utilities-*-sources.jar" />
		</delete>
		<get src="https://soderer.de/maven2/de/soderer/JavaUtilities/${soderer-utilities.version}/soderer-utilities-${soderer-utilities.version}-sources.jar" dest="lib/" />
	</target>

	<!-- SWT Windows: JarInJarLoader decides by OS type which SWT jar to load-->
	<!-- https://archive.eclipse.org/eclipse/downloads/ -->
	<!-- https://mirrors.dotsrc.org/eclipse/eclipse/downloads/drops4 -->
	<available file="lib/swt-${swt.version}-win32-win32-x86_64.jar" property="swt-win.available" />
	<target name="get_swt_win" unless="swt-win.available" depends="proxy">
		<mkdir dir="lib/" />
		<delete>
			<fileset dir="lib" includes="swt-*-win32-win32-x86_64.jar" />
		</delete>
		<get src="https://mirrors.dotsrc.org/eclipse/eclipse/downloads/drops4/${swt.build}/swt-${swt.version}-win32-win32-x86_64.zip" dest="lib/swt_win.zip" />
		<unzip src="lib/swt_win.zip" dest="lib/swt_win" />
		<move file="lib/swt_win/swt.jar" tofile="lib/swt-${swt.version}-win32-win32-x86_64.jar" />
		<delete dir="lib/swt_win" />
		<delete file="lib/swt_win.zip" />
	</target>

	<!-- SWT Linux: JarInJarLoader decides by OS type which SWT jar to load-->
	<!-- https://archive.eclipse.org/eclipse/downloads/ -->
	<!-- https://mirrors.dotsrc.org/eclipse/eclipse/downloads/drops4 -->
	<available file="lib/swt-${swt.version}-gtk-linux-x86_64.jar" property="swt-linux.available" />
	<target name="get_swt_linux" unless="swt-linux.available" depends="proxy">
		<mkdir dir="lib/" />
		<delete>
			<fileset dir="lib" includes="swt-*-gtk-linux-x86_64.jar" />
		</delete>
		<get src="https://mirrors.dotsrc.org/eclipse/eclipse/downloads/drops4/${swt.build}/swt-${swt.version}-gtk-linux-x86_64.zip" dest="lib/swt_linux.zip" />
		<unzip src="lib/swt_linux.zip" dest="lib/swt_linux" />
		<move file="lib/swt_linux/swt.jar" tofile="lib/swt-${swt.version}-gtk-linux-x86_64.jar" />
		<delete dir="lib/swt_linux" />
		<delete file="lib/swt_linux.zip" />
	</target>

	<target name="download_dependencies" depends="get_mailapi, get_json, get_proxyautoconfig, get_network, get_soderer_utilities, get_soderer_utilities_sources, get_swt_win, get_swt_linux" />

	<target name="compile" depends="download_dependencies">
		<path id="build.classpath">
			<fileset dir="lib">
				<include name="*.jar" />
			</fileset>
		</path>

		<javac release="17" debug="true" nowarn="true" deprecation="false" destdir="${buildPath}/bin" fork="yes" srcdir="src" includeantruntime="false" encoding="UTF-8" classpath="lib/*">
			<classpath refid="build.classpath" />
			<compilerarg value="-Xlint:unchecked" />
			<compilerarg value="-parameters" />
		</javac>

		<copy todir="${buildPath}/bin">
			<fileset dir="src/main/resources">
				<include name="**/LanguageProperties*.properties" />
				<include name="**/*.txt" />
				<include name="**/*.pem" />
				<include name="**/*.png" />
				<include name="**/*.ico" />
			</fileset>
		</copy>

		<replace file="${buildPath}/bin/VersionInfo.txt" token="$${build.version}" value="${build.version}"/>
	</target>

	<target name="create_versionfile">
		<basename property="CaPublicKeyFileName" file="${CaPublicKey}"/>
		<basename property="CaPublicKeyFileNameOld" file="${CaPublicKeyOld}"/>

		<delete file="${buildPath}/bin/application_version.txt" />
		<echo file="${buildPath}/bin/application_version.txt" append="false">${build.version}${line.separator}${buildTime}${line.separator}${VersionsUrl}${line.separator}${CaPublicKeyFileName}, ${CaPublicKeyFileNameOld}${line.separator}</echo>
		<delete file="src/main/resources/application_version.txt" />
		<echo file="src/main/resources/application_version.txt" append="false">${build.version}${line.separator}${buildTime}${line.separator}${VersionsUrl}${line.separator}${CaPublicKeyFileName}, ${CaPublicKeyFileNameOld}${line.separator}</echo>
	</target>

	<target name="create_jar" depends="create_versionfile, compile">
		<jar destfile="${buildPath}/RestClient.jar">
			<manifest>
				<attribute name="Main-Class" value="de.soderer.RestClient" />
				<attribute name="Rsrc-Main-Class" value="de.soderer.restclient.RestClient" />
				<attribute name="Class-Path" value="." />
			</manifest>

			<fileset dir="${buildPath}/bin" />

			<zipfileset file="${CaPublicKey}" />
			<zipfileset file="${CaPublicKeyOld}" />
			<zipfileset dir="lib" includes="*.jar" excludes="*sources.jar" />
		</jar>
	</target>

	<target name="sign_jar" depends="create_versionfile, compile, create_jar" if="codeSigningPropertiesAvailable">
		<signjar destDir="${buildPath}" alias="${CodeSigningKeyAlias}" keystore="${CodeSigningKeyStore}" storepass="${CodeSigningKeyStorePassword}" keypass="${CodeSigningKeyPassword}" preservelastmodified="true" tsaurl="${TsaUrl}">
			<path>
				<fileset dir="${buildPath}" includes="RestClient.jar" />
			</path>
		</signjar>

		<copy file="${buildPath}/RestClient.jar" tofile="${buildPath}/RestClient-${build.version}.jar" />
	</target>

	<macrodef name="unsignjar">
		<attribute name="jar" />
		<sequential>
			<!-- Remove any existing signatures from a JAR file. -->
			<tempfile prefix="unsignjar-" destdir="${java.io.tmpdir}" property="temp.file" />
			<echo message="Removing signatures from JAR: @{jar}" />
			<mkdir dir="${temp.file}" />
			<unjar src="@{jar}" dest="${temp.file}">
				<patternset>
					<include name="**" />
					<exclude name="META-INF/*.SF" />
					<exclude name="META-INF/*.DSA" />
					<exclude name="META-INF/*.RSA" />
				</patternset>
			</unjar>
			<delete file="@{jar}" failonerror="true" />
			<!-- Touch META-INF/MANIFEST.MF in case the jar file didn't have a manifest. Otherwise the JAR task below will fail if the manifest file doesn't exist. -->
			<mkdir dir="${temp.file}/META-INF" />
			<touch file="${temp.file}/META-INF/MANIFEST.MF" />
			<jar destfile="@{jar}" basedir="${temp.file}" includes="**" manifest="${temp.file}/META-INF/MANIFEST.MF" />
			<delete dir="${temp.file}" failonerror="true" />
		</sequential>
	</macrodef>

	<target name="cleanup_after">
		<delete dir="${buildPath}/bin" />
	</target>
</project>
